version: 1.2

workflows:
  - name: calculate_MQband_histogram
    subclass: WDL
    primaryDescriptorPath: /scripts/calculate_MQband_wdl/calculate_MQband_histogram.wdl
    testParameterFiles:
      - empty.json
    filters:
      branches:
        - wdl_loc_opt
  - name: import_genomes
    subclass: WDL
    primaryDescriptorPath: /scripts/import_genomes_wdl/import_genomes.wdl
    testParameterFiles:
      - empty.json
    filters:
      branches:
        - wdl_loc_opt
  - name: reblock-gvcf-BQ
    subclass: WDL
    primaryDescriptorPath: /scripts/reblock_gvcf_bq_wdl/reblock_gvcf_bq.wdl
    testParameterFiles:
      - empty.json
    filters:
      branches:
       - wdl_loc_opt
